apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploymnet
  labels:
    app: myapp
    type: front-end
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-replicaset
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 6
