apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-ontroller
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: pod-demo-1
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2